### ISSUE TITLE
Can't sign up.

### ISSUE THREAD

**Issue by lukasito2011** [stepmania/stepmania-site#71]
I'm trying to sign up at stepmania.com but I can't. It just says "Registration is disabled due to spammers maxing out our CPU. If you need support try GitHub or IRC." so I want to see the reason why it does not want me to create a account.
 
<img width="960" alt="problem" src="https://user-images.githubusercontent.com/89336096/133668450-180d2e71-2fb7-41e7-ad0b-ebe73d272ef5.png">

**Comment by shakesoda** [comment]
it's disabled because to prevent the spam problems too much work needs to be done and it needs too much ongoing upkeep. it was getting thousands of spam messages and users per day, even with captchas and such to mitigate it, and i never built good enough anti-spam tools to deal with the cleanup. it's largely still up for historical reasons and ongoing posts in things like people's simfile threads, but at some point i should probably redirect the entire thing to github discussions instead -> https://github.com/stepmania/stepmania/discussions
